DROP DATABASE IF EXISTS employee_mgmtDB;

CREATE DATABASE employee_mgmtDB;

USE employee_mgmtDB;

CREATE TABLE department(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(30) NULL,
    create_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    created_by VARCHAR(30) NOT NULL,
    update_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by VARCHAR(30) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE emp_role(
	id INT NOT NULL AUTO_INCREMENT,
    title VARCHAR(30) NULL,
    salary DECIMAL(10,2) NULL,
    department_id INT NULL,
    create_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(30) NOT NULL,
    update_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	updated_by VARCHAR(30) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_dept FOREIGN KEY (department_id) REFERENCES department(id)
		 ON UPDATE CASCADE ON DELETE SET NULL 
);

CREATE TABlE employee(
	id INT NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(30) NULL,
    last_name VARCHAR(30) NULL,
    role_id INT NOT NULL ,
    manager_id INT NULL,    
    create_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    created_by VARCHAR(30) NOT NULL,
    update_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by VARCHAR(30) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_emprole FOREIGN KEY (role_id) REFERENCES emp_role(id)  ON UPDATE CASCADE ON DELETE RESTRICT ,
    CONSTRAINT fk_emp FOREIGN KEY (manager_id) REFERENCES employee(id)  ON UPDATE CASCADE ON DELETE SET NULL 
);


